# Generated by Django 6.0 on 2026-01-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='credit_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
