# Generated by Django 6.0 on 2026-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_alter_creditledger_credit_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditwallet',
            name='credit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
