# Generated by Django 6.0 on 2026-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_creditwallet_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='idempotency_key',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
