# Generated by Django 6.0 on 2026-01-20 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentkey', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('order_id', models.CharField(default='20260120_20ac06c6f84440ae8feaeaebe772b648', max_length=64, unique=True)),
                ('order_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('READY', '대기'), ('DONE', '완료'), ('ABORTED', '실패'), ('CANCELED', '취소')], default='READY', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toss_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
