# Generated by Django 6.0 on 2025-12-29 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentkey', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('order_id', models.CharField(default='20251229_88127424f6ff447cbaa756898fd6757d', max_length=64, unique=True)),
                ('order_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
