# Generated by Django 6.0 on 2025-12-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toss',
            name='status',
            field=models.CharField(choices=[('READY', '대기'), ('PAID', '완료'), ('FAILED', '실패')], default='READY', max_length=10),
        ),
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251229_562726cddcdb43f4851d0870b2000ef1', max_length=64, unique=True),
        ),
    ]
