# Generated by Django 6.0 on 2026-01-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260120_0ff1e5159dd4468494a4481f52dc0882', max_length=64, unique=True),
        ),
    ]
