# Generated by Django 6.0 on 2026-01-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260120_a4d2fb60e69943abadbf1157f5356e4a', max_length=64, unique=True),
        ),
    ]
