# Generated by Django 6.0 on 2025-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_toss_status_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251229_99331d7a630f41f586f5f871b378c109', max_length=64, unique=True),
        ),
    ]
