# Generated by Django 6.0 on 2026-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260120_5c82ed1dc7ae46048fbd1ea75b1a380f', max_length=64, unique=True),
        ),
    ]
