# Generated by Django 6.0 on 2025-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_toss_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toss',
            old_name='paymentkey',
            new_name='paymentKey',
        ),
        migrations.RemoveField(
            model_name='toss',
            name='order_id',
        ),
        migrations.AddField(
            model_name='toss',
            name='orderId',
            field=models.CharField(default='20251229_b6b95f32b8d54235831e0d2d95262f22', max_length=64, unique=True),
        ),
    ]
