# Generated by Django 6.0 on 2026-01-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260120_885921a8303f46d5a3c84ee1d9d5928e', max_length=64, unique=True),
        ),
    ]
