# Generated by Django 6.0 on 2025-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_paymentkey_toss_paymentkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='orderId',
            field=models.CharField(default='20251229_a85034d2367a46338c536edb6f5e3b53', max_length=64, unique=True),
        ),
    ]
