# Generated by Django 6.0 on 2026-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260120_a952b8f80ca24b3c9de815ebb34bc532', max_length=64, unique=True),
        ),
    ]
