# Generated by Django 6.0 on 2025-12-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_toss_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='orderId',
            field=models.CharField(default='20251229_10fa587b857d47dcbdd379543fd3c326', max_length=64, unique=True),
        ),
    ]
