# Generated by Django 6.0 on 2025-12-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_toss_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toss',
            old_name='paymentKey',
            new_name='paymentkey',
        ),
        migrations.RemoveField(
            model_name='toss',
            name='orderId',
        ),
        migrations.AddField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251229_c59aeacf63524da2871b30aa133fd1e6', max_length=64, unique=True),
        ),
    ]
