# Generated by Django 6.0 on 2025-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_rename_paymentkey_toss_paymentkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251229_d6a04f33c7c647c280e68fa52fc82384', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='toss',
            name='paymentkey',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
