# Generated by Django 6.0 on 2025-12-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_toss_order_id_alter_toss_paymentkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251229_f69e857f4a0e4f69a9d21122ddfdc9c5', max_length=64, unique=True),
        ),
    ]
