# Generated by Django 6.0 on 2025-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251229_840b981133c041cd9306d47922fc80a6', max_length=64, unique=True),
        ),
    ]
