# Generated by Django 6.0 on 2025-12-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251230_2427907e6e874b4b9ebd5d1d36624b48', max_length=64, unique=True),
        ),
    ]
