# Generated by Django 6.0 on 2025-12-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251230_3c88ab634ac243cfbcb2313534f41aeb', max_length=64, unique=True),
        ),
    ]
