# Generated by Django 6.0 on 2025-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251230_3006ec6774864d43b693859470b98826', max_length=64, unique=True),
        ),
    ]
