# Generated by Django 6.0 on 2025-12-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251230_7d5dfa717785405184617c193e7e5e48', max_length=64, unique=True),
        ),
    ]
