# Generated by Django 6.0 on 2025-12-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251230_9fa1c69cfb5c44648fc348e71a92ca8e', max_length=64, unique=True),
        ),
    ]
