# Generated by Django 6.0 on 2025-12-30 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_toss_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toss',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toss_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251230_91313b8fd44b4bde914f6d86c0c1d5c0', max_length=64, unique=True),
        ),
    ]
