# Generated by Django 6.0 on 2025-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_toss_user_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251230_e5a04ebe9e7e43c0af15d5116cc61fc0', max_length=64, unique=True),
        ),
    ]
