# Generated by Django 6.0 on 2025-12-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251230_63ea620614e4401e96e559da21878478', max_length=64, unique=True),
        ),
    ]
