# Generated by Django 6.0 on 2025-12-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251231_d30f8d9e45154ed9b0344375c7aa5902', max_length=64, unique=True),
        ),
    ]
