# Generated by Django 6.0 on 2025-12-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20251231_11750db335e54b14a651fa1c0cb72409', max_length=64, unique=True),
        ),
    ]
