# Generated by Django 6.0 on 2026-01-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260101_a11ef62f4de343ffbb4c58344c07373c', max_length=64, unique=True),
        ),
    ]
