# Generated by Django 6.0 on 2026-01-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260102_1e89eeee6267467ab7708d17686d7e80', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='toss',
            name='status',
            field=models.CharField(choices=[('READY', '대기'), ('PAID', '완료'), ('ABORTED', '실패'), ('CANCELED', '취소')], default='READY', max_length=10),
        ),
    ]
