# Generated by Django 6.0 on 2026-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_alter_toss_order_id_alter_toss_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260102_8c5a5b6350174ff0a483dc1c50ed61e7', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='toss',
            name='status',
            field=models.CharField(choices=[('READY', '대기'), ('DONE', '완료'), ('ABORTED', '실패'), ('CANCELED', '취소')], default='READY', max_length=10),
        ),
    ]
