# Generated by Django 6.0 on 2026-01-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_toss_order_id_alter_toss_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260102_724c822feed346a299d564629a268e82', max_length=64, unique=True),
        ),
    ]
