# Generated by Django 6.0 on 2026-01-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260105_9eff966c425144daa861e68121826052', max_length=64, unique=True),
        ),
    ]
