# Generated by Django 6.0 on 2026-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260106_d3533577ea4346638585c751e92a4595', max_length=64, unique=True),
        ),
    ]
