# Generated by Django 6.0 on 2026-01-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260106_4cb15c9709da42edbb6531f970d3a454', max_length=64, unique=True),
        ),
    ]
