# Generated by Django 6.0 on 2026-01-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260106_b50ca88e40bf46b2a89c98576582a002', max_length=64, unique=True),
        ),
    ]
