# Generated by Django 6.0 on 2026-01-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260106_101c79c255f64007a232e92345c0dd0a', max_length=64, unique=True),
        ),
    ]
