# Generated by Django 6.0 on 2026-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260106_e55d011557114c03833319f0bc7a63e7', max_length=64, unique=True),
        ),
    ]
