# Generated by Django 6.0 on 2026-01-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260107_d4f2bb80e267448c88ae10fad40171dc', max_length=64, unique=True),
        ),
    ]
