# Generated by Django 6.0 on 2026-01-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260108_eeb56d6a9fca4c81a159d5b2fcd3de86', max_length=64, unique=True),
        ),
    ]
