# Generated by Django 6.0 on 2026-01-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260108_0a4fae09fbc849fc894cbc814ca593cf', max_length=64, unique=True),
        ),
    ]
