# Generated by Django 6.0 on 2026-01-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260112_aeffef8f3633435488f135233551eede', max_length=64, unique=True),
        ),
    ]
