# Generated by Django 6.0 on 2026-01-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260112_4fdd93bb1d21480189736aef5bd6edd8', max_length=64, unique=True),
        ),
    ]
