# Generated by Django 6.0 on 2026-01-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260113_93a704c799864fc7b233c754e6d2b2d4', max_length=64, unique=True),
        ),
    ]
