# Generated by Django 6.0 on 2026-01-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0036_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260113_33d68a82409643abb5a847c4dd65e9d2', max_length=64, unique=True),
        ),
    ]
