# Generated by Django 6.0 on 2026-01-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260113_e82dc4fd043a49d592e4be47413055b6', max_length=64, unique=True),
        ),
    ]
