# Generated by Django 6.0 on 2026-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0038_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260113_f44228342891488d879ceab194a950ae', max_length=64, unique=True),
        ),
    ]
