# Generated by Django 6.0 on 2026-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260113_d602895e1d034baab20024cffd6bf1cf', max_length=64, unique=True),
        ),
    ]
