# Generated by Django 6.0 on 2026-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260113_d532fb6f610c4968b6ca03c004f1f4ea', max_length=64, unique=True),
        ),
    ]
