# Generated by Django 6.0 on 2026-01-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0041_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260113_c2cf42a1395341dc9b66ba87db917c5a', max_length=64, unique=True),
        ),
    ]
