# Generated by Django 6.0 on 2026-01-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0042_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260113_e307a193be244cd198955bf8fc39d226', max_length=64, unique=True),
        ),
    ]
