# Generated by Django 6.0 on 2026-01-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0043_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260114_0def0c78b4d74774b66978c033d62132', max_length=64, unique=True),
        ),
    ]
