# Generated by Django 6.0 on 2026-01-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0044_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260114_1199be1cf1f54ff3a47535edd6f6042a', max_length=64, unique=True),
        ),
    ]
