# Generated by Django 6.0 on 2026-01-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0045_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260114_0c5dbe2ed3724059b20eb1221f7a13b8', max_length=64, unique=True),
        ),
    ]
