# Generated by Django 6.0 on 2026-01-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0046_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260114_3e3759ad8ab044b2aa336f368703d387', max_length=64, unique=True),
        ),
    ]
