# Generated by Django 6.0 on 2026-01-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0047_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260114_e0a3a940b4c644ed9153f0a805e80090', max_length=64, unique=True),
        ),
    ]
