# Generated by Django 6.0 on 2026-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0048_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260119_bb30098328e54342969445e0ac0d4e62', max_length=64, unique=True),
        ),
    ]
