# Generated by Django 6.0 on 2026-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0049_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260119_f7ba183caf0c47c2b96a6304f692e697', max_length=64, unique=True),
        ),
    ]
