# Generated by Django 6.0 on 2026-01-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0050_alter_toss_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toss',
            name='order_id',
            field=models.CharField(default='20260119_53a536ecd8b74d898bae8701c80a4369', max_length=64, unique=True),
        ),
    ]
