# Generated by Django 6.0 on 2026-01-20 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hard_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'created_at', 'author', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InquiryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sample/%Y/%m/%d/')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='inquires.inquiry')),
            ],
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['-created_at', 'created_at', 'author', 'title'], name='inquires_in_created_99cca2_idx'),
        ),
    ]
