# Generated by Django 6.0 on 2026-01-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
