# Generated by Django 6.0 on 2026-01-13 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquires', '0002_inquiry_deleted_at_inquiry_is_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at', 'created_at']},
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['-created_at', 'created_at'], name='inquires_in_created_6b9ecf_idx'),
        ),
    ]
