# Generated by Django 6.0 on 2026-01-13 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquires', '0003_alter_inquiry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at', 'created_at', 'author']},
        ),
        migrations.RemoveIndex(
            model_name='inquiry',
            name='inquires_in_created_6b9ecf_idx',
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['-created_at', 'created_at', 'author'], name='inquires_in_created_16fb96_idx'),
        ),
    ]
