# Generated by Django 6.0 on 2026-01-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquires', '0005_alter_inquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='hard_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
