# Generated by Django 6.0 on 2026-01-14 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquires', '0006_inquiry_hard_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sample/%Y/%m/%d/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='inquires.inquiry')),
            ],
        ),
    ]
