# Generated by Django 6.0 on 2026-01-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquires', '0007_inquiryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiryimage',
            old_name='post',
            new_name='inquiry',
        ),
    ]
