# Generated by Django 6.0 on 2025-12-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit',
        ),
    ]
